Repository algorandfoundation/nodekit, pull requests merged in 2024-12, with the labels that each got.

#33 feat: incentive eligibility check for automated fees
  codecov.yaml
  internal/accounts.go
  internal/participation.go
  internal/participation_test.go
  internal/test/client.go
  ui/internal/test/state.go
  ui/modal/testdata/Test_Snapshot/TransactionModal.golden
  ui/modals/transaction/controller.go
  ui/modals/transaction/testdata/Test_Snapshot/Offline.golden
  ui/modals/transaction/testdata/Test_Snapshot/Online.golden
  ui/modals/transaction/view.go
Labels: feature

#32 fix(ui): overflow message for modals
  ui/style/style.go
  ui/style/style_test.go
Labels: bug

#30 Feat/generate modal validation
  internal/accounts.go
  ui/modals/generate/controller.go
  ui/modals/generate/generate_test.go
  ui/modals/generate/model.go
  ui/modals/generate/testdata/Test_Snapshot/Waiting.golden
  ui/modals/generate/view.go
  ui/modals/transaction/testdata/Test_Snapshot/NotVisible.golden
  ui/modals/transaction/view.go
  ui/viewport.go
  ui/viewport_test.go
Labels: feature

#31 change duration modes to day/month/rounds
  internal/rangetype.go
  ui/app/app_test.go
  ui/app/keys.go
  ui/modals/generate/controller.go
  ui/modals/generate/generate_test.go
  ui/modals/generate/model.go
Labels: task

#35 Chore/prettify error messages
  cmd/root.go
  cmd/root_test.go
  cmd/status.go
  cmd/status_test.go
  main_test.go
  ui/explanations/explanations.go
  ui/style/style.go
Labels: task

#36 fix: show expired keys
  cmd/root.go
  internal/accounts.go
  internal/accounts_test.go
  internal/state.go
  internal/test/client.go
  internal/test/mock/fixtures.go
  ui/internal/test/state.go
  ui/pages/accounts/model.go
Labels: feature

#38 docs: update readme to latest
  CONTRIBUTING.md
  README.md
  install.sh
Labels: documentation

#34 release: v1.0.0-beta.1
  .github/workflows/CD.yaml
Labels: task

#44 fix: fast-catchup detection
  internal/state.go
  internal/status.go
Labels: bug

#46 feat: url shortener
  cmd/root.go
  internal/http.go
  internal/participation.go
  internal/participation_test.go
  internal/state.go
  ui/app/url.go
  ui/internal/test/state.go
  ui/modal/controller.go
  ui/modal/modal_test.go
  ui/modal/model.go
  ui/modal/testdata/Test_Snapshot/TransactionModal.golden
  ui/modals/info/info.go
  ui/modals/transaction/model.go
  ui/modals/transaction/testdata/Test_Snapshot/NotVisible.golden
  ui/modals/transaction/testdata/Test_Snapshot/Offline.golden
  ui/modals/transaction/testdata/Test_Snapshot/Online.golden
  ui/modals/transaction/testdata/Test_Snapshot/Unsupported.golden
  ui/modals/transaction/transaction_test.go
  ui/modals/transaction/view.go
Labels: feature

#50 fix: install script banner
  install.sh
Labels: bug

#25 feat: Node Install, Start, Stop, Upgrade ENG-572
  .docker/Fedora.dockerfile
  .docker/Ubuntu.dockerfile
  .github/workflows/code_test.yaml
  .github/workflows/node_test.yaml
  .gitignore
  Makefile
  cmd/configure/configure.go
  cmd/configure/service.go
  cmd/configure/utils.go
  cmd/node/debug.go
  cmd/node/install.go
  cmd/node/node.go
  cmd/node/start.go
  cmd/node/stop.go
  cmd/node/uninstall.go
  cmd/node/upgrade.go
  cmd/root.go
  cmd/status.go
  cmd/status_test.go
  codecov.yaml
  docker-compose.integration.yaml
  go.mod
  go.sum
  internal/algod/algod.go
  internal/algod/fallback/algod.go
  internal/algod/linux/linux.go
  internal/algod/mac/mac.go
  internal/algod/msgs/errors.go
  internal/algod/utils/utils.go
  internal/system/cmds.go
  internal/system/service.go
  main.go
  main_test.go
  playbook.yaml
  ui/README.md
  ui/app/app_test.go
  ui/style/style.go
Labels: feature

#51 Chore/quick fixes
  cmd/node/install.go
  cmd/node/upgrade.go
  internal/algod/linux/linux.go
  ui/modal/testdata/Test_Snapshot/InfoModal.golden
  ui/modals/info/info.go
  ui/modals/info/testdata/Test_Snapshot/Visible.golden
  ui/modals/transaction/view.go
Labels: task
