Repository algorandfoundation/nodekit, pull requests merged in 2024-10, with the labels that each got.

#2 feat: add basic skeleton cli
  .docker/algod_config.json
  .docker/algod_network_template.json
  .gitignore
  Dockerfile
  Makefile
  api/lf.go
  cmd/root.go
  cmd/root_test.go
  cmd/status.go
  cmd/status_test.go
  cmd/testdata/algod.admin.token
  cmd/testdata/config.json
  docker-compose.yaml
  generate.yaml
  go.mod
  go.sum
  internal/status.go
  internal/status_test.go
  main.go
  main_test.go
  ui/status.go
  ui/status_test.go
  ui/style.go
  ui/utils.go
Labels: feature

#5 feat: participation key management
  .docker/run.sh
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  api/lf.go
  assets/Banner.gif
  assets/TUI.png
  cmd/README.md
  cmd/root.go
  cmd/status.go
  docker-compose.yaml
  generate.yaml
  go.mod
  go.sum
  internal/README.md
  internal/accounts.go
  internal/metrics.go
  internal/participation.go
  internal/participation_test.go
  internal/state.go
  internal/status.go
  internal/status_test.go
  scripts/wallet.mjs
  ui/README.md
  ui/controls.go
  ui/controls/controller.go
  ui/controls/controls_test.go
  ui/controls/model.go
  ui/controls/style.go
  ui/controls/view.go
  ui/pages/accounts/cmds.go
  ui/pages/accounts/controller.go
  ui/pages/accounts/model.go
  ui/pages/accounts/style.go
  ui/pages/accounts/view.go
  ui/pages/generate/controller.go
  ui/pages/generate/model.go
  ui/pages/generate/style.go
  ui/pages/generate/view.go
  ui/pages/keys/cmds.go
  ui/pages/keys/controller.go
  ui/pages/keys/model.go
  ui/pages/keys/style.go
  ui/pages/keys/view.go
  ui/pages/style.go
  ui/pages/transaction/controller.go
  ui/pages/transaction/model.go
  ui/pages/transaction/view.go
  ui/protocol.go
  ui/protocol_test.go
  ui/status.go
  ui/status_test.go
  ui/style.go
  ui/utils.go
  ui/utils/utils.go
  ui/viewport.go
  ui/viewport_test.go
Labels: feature

#6 feat: metrics RPC endpoint and parser
  internal/accounts.go
  internal/metrics.go
  internal/metrics_test.go
  internal/state.go
  internal/state_test.go
Labels: feature

#7 feat: TPS and average round times
  internal/block.go
  internal/block_test.go
  internal/state.go
  internal/status.go
Labels: feature

#8 feat: sync status and latest round
  cmd/root.go
  internal/state.go
  internal/status.go
Labels: feature

#11 fix: catchup and zero tc blocks
  cmd/root.go
  internal/block.go
  internal/state.go
  ui/error.go
  ui/style.go
  ui/viewport.go
Labels: bug, feature

#9 feat: check for updates from github
  internal/github.go
  internal/status.go
Labels: feature

#12 chore: add startup scripts for different environments
  .docker/algod_config.json
  .docker/algod_network_template.json
  .docker/run.sh
  .docker/start_all.sh
  .docker/start_dev.sh
  .docker/start_empty.sh
  .docker/start_fast_catchup.sh
  Dockerfile
  docker-compose.yaml
Labels: task

#15 test: internal/accounts.go
  .github/workflows/test.yaml
  api/lf.go
  generate.yaml
  go.mod
  internal/accounts.go
  internal/accounts_test.go
  ui/pages/transaction/controller.go
Labels: task

#17 feat: border titles
  ui/protocol.go
  ui/status.go
  ui/style.go
Labels: feature

#16 fix: improve resilience and error handling
  cmd/root.go
  cmd/root_test.go
  internal/block.go
  internal/state.go
  main_test.go
  ui/viewport.go
Labels: bug

#19 refactor: style, borders, and adds more account state
  api/lf.go
  cmd/root.go
  cmd/status.go
  internal/accounts.go
  internal/accounts_test.go
  internal/block.go
  internal/state.go
  internal/time.go
  ui/error.go
  ui/pages/accounts/controller.go
  ui/pages/accounts/model.go
  ui/pages/accounts/style.go
  ui/pages/accounts/view.go
  ui/pages/generate/cmds.go
  ui/pages/generate/controller.go
  ui/pages/generate/model.go
  ui/pages/generate/style.go
  ui/pages/generate/view.go
  ui/pages/keys/controller.go
  ui/pages/keys/model.go
  ui/pages/keys/style.go
  ui/pages/keys/view.go
  ui/pages/style.go
  ui/pages/transaction/style.go
  ui/pages/transaction/view.go
  ui/protocol.go
  ui/protocol_test.go
  ui/status.go
  ui/status_test.go
  ui/style.go
  ui/style/style.go
  ui/viewport.go
Labels: task
