Repository algorandfoundation/nodekit, pull requests merged in 2025-01, with the labels that each got.

#55 feat: add fast-catchup state to status
  internal/algod/state.go
  internal/algod/status.go
  internal/algod/status_test.go
  ui/modal/controller.go
Labels: feature

#52 feat: bootstrap command
  .docker/Fedora.dockerfile
  .docker/Ubuntu.dockerfile
  .docker/start_all.sh
  .docker/start_dev.sh
  .docker/start_empty.sh
  .docker/start_fast_catchup.sh
  .github/workflows/code_test.yaml
  .github/workflows/node_test.yaml
  Dockerfile
  Makefile
  cmd/bootstrap.go
  cmd/catchup/catchup.go
  cmd/catchup/debug.go
  cmd/catchup/start.go
  cmd/catchup/stop.go
  cmd/configure/configure.go
  cmd/configure/network.go
  cmd/configure/service.go
  cmd/configure/utils.go
  cmd/debug.go
  cmd/install.go
  cmd/node/catchup/catchup.go
  cmd/node/node.go
  cmd/node/sync.go
  cmd/root.go
  cmd/start.go
  cmd/stop.go
  cmd/uninstall.go
  cmd/upgrade.go
  cmd/utils/config.go
  cmd/utils/explanations/errors.go
  cmd/utils/explanations/explanations.go
  cmd/utils/flags.go
  docker-compose.integration.yaml
  docker-compose.yaml
  go.mod
  go.sum
  internal/algod/accounts_test.go
  internal/algod/catchpoint.go
  internal/algod/client.go
  internal/algod/mac/mac.go
  internal/algod/state.go
  internal/algod/state_test.go
  internal/algod/status.go
  internal/algod/status_test.go
  internal/algod/utils/utils.go
  playbook.yaml
  ui/app/bootstrap.go
  ui/app/emitter.go
  ui/bootstrap/model.go
  ui/modal/controller.go
  ui/style/style.go
  ui/viewport.go
Labels: feature, refactor

#56 chore: alert user when going online/generates new key
  internal/algod/status.go
  ui/app/keys.go
  ui/app/modal.go
  ui/modal/controller.go
  ui/modal/model.go
  ui/modals/info/info.go
Labels: feature

#59 docs: hand crafted docs
  README.md
  assets/Banner.gif
  assets/TUI.png
  assets/footer.md
  assets/nodekit.png
  docs/.gitignore
  docs/README.md
  docs/astro.config.mjs
  docs/nodekit.png
  docs/package-lock.json
  docs/package.json
  docs/public/favicon.svg
  docs/public/nodekit.png
  docs/src/content.config.ts
  docs/src/content/docs/guides/example.md
  docs/src/content/docs/reference/algorun.md
  docs/src/content/docs/reference/algorun_bootstrap.md
  docs/src/content/docs/reference/algorun_catchup.md
  docs/src/content/docs/reference/algorun_catchup_debug.md
  docs/src/content/docs/reference/algorun_catchup_start.md
  docs/src/content/docs/reference/algorun_catchup_stop.md
  docs/src/content/docs/reference/algorun_configure.md
  docs/src/content/docs/reference/algorun_configure_service.md
  docs/src/content/docs/reference/algorun_debug.md
  docs/src/content/docs/reference/algorun_install.md
  docs/src/content/docs/reference/algorun_start.md
  docs/src/content/docs/reference/algorun_stop.md
  docs/src/content/docs/reference/algorun_uninstall.md
  docs/src/content/docs/reference/algorun_upgrade.md
  docs/src/pages/index.astro
  docs/src/tailwind.css
  docs/tailwind.config.mjs
  docs/tsconfig.json
  man/algorun_bootstrap.md
  man/algorun_catchup.md
  man/algorun_catchup_debug.md
  man/algorun_catchup_start.md
  man/algorun_catchup_stop.md
  man/algorun_configure.md
  man/algorun_configure_service.md
  man/algorun_debug.md
  man/algorun_install.md
  man/algorun_start.md
  man/algorun_stop.md
  man/algorun_uninstall.md
  man/algorun_upgrade.md
  scripts/documentation.go
  ui/style/style.go
Labels: documentation

#61 fix: bootstrap refinements
  cmd/bootstrap.go
  ui/bootstrap/model.go
Labels: bug

#40 release: v1.0.0
  .github/workflows/CD.yaml
Labels: task

#83 chore: truncate token in debug command
  cmd/debug.go
Labels: task

#84 fix: existing algorand data environment
  cmd/bootstrap.go
Labels: bug

#87 security: patch golang.org/x/net
  go.mod
  go.sum
Labels: task

#88 chore: move logger to top of cmd loop
  internal/system/cmds.go
Labels: task

#95 cd: skip upload when there is no version
  .github/workflows/CD.yaml
Labels: task

#92 chore: add ui improvement template
  .github/ISSUE_TEMPLATE/💄-ui-improvement.md
Labels: task

#104 chore: use autostyle for bootstrap questions
  ui/bootstrap/model.go
Labels: task

#105 docs: add decisions, cleanup contributing and scripts
  .DS_Store
  .decisions/2-Release-Cycle.md
  .decisions/3-Node-Management.md
  .decisions/README.md
  .gitignore
  .tapes/README.md
  .tapes/tui.tape
  CONTRIBUTING.md
  LICENSE
  assets/tapes/tui.gif
  scripts/README.md
  scripts/wallet.json
  scripts/wallet.mjs
Labels: task

#113 chore: improve active key detection
  internal/algod/state.go
Labels: task

#101 fix: add update for brew
  internal/algod/mac/mac.go
Labels: bug

#119 feat: enable incentive eligibility fees
  cmd/bootstrap.go
  cmd/root.go
  internal/algod/participation/participation.go
  internal/algod/state.go
  internal/algod/status.go
  ui/modals/transaction/controller.go
  ui/modals/transaction/view.go
Labels: feature

#107 fix: improve command error handling
  cmd/utils/flags.go
  internal/system/cmds.go
Labels: task

#103 chore: skip questions when already bootstrapped
  cmd/bootstrap.go
  cmd/root.go
Labels: task

#125 fix: wait for status from unstable clients
  cmd/bootstrap.go
  internal/algod/algod.go
  internal/algod/client.go
  ui/bootstrap/model.go
Labels: bug

#124 Feat/accounts page add incentive eligibility, fix: non-resident keys in txn modal
  ui/modal/controller.go
  ui/modal/model.go
  ui/modals/info/info.go
  ui/modals/transaction/model.go
  ui/pages/accounts/model.go
  ui/pages/accounts/testdata/Test_Snapshot/Visible.golden
Labels: task

#130 feat: toggle between QRCode and deep-link
  ui/modal/modal_test.go
  ui/modals/info/info.go
  ui/modals/transaction/controller.go
  ui/modals/transaction/model.go
  ui/modals/transaction/transaction_test.go
  ui/modals/transaction/view.go
  ui/viewport.go
Labels: feature

#133 fix: deterministic state while detecting corrupt keys
  internal/algod/participation/participation.go
  ui/modal/controller.go
  ui/modal/model.go
Labels: bug

#129 v1.2.0
  README.md
  cmd/bootstrap.go
  cmd/debug.go
  cmd/root.go
  cmd/utils/flags.go
  docs/src/content/docs/reference/nodekit.md
  docs/src/pages/index.astro
  go.mod
  internal/algod/algod.go
  internal/algod/client.go
  internal/algod/mac/mac.go
  internal/algod/participation/participation.go
  internal/algod/state.go
  internal/algod/status.go
  internal/algod/utils/utils.go
  internal/system/cmds.go
  main.go
  ui/bootstrap/model.go
  ui/modal/controller.go
  ui/modal/modal_test.go
  ui/modal/model.go
  ui/modal/testdata/Test_Snapshot/InfoModal.golden
  ui/modals/info/info.go
  ui/modals/info/testdata/Test_Snapshot/Visible.golden
  ui/modals/transaction/controller.go
  ui/modals/transaction/model.go
  ui/modals/transaction/transaction_test.go
  ui/modals/transaction/view.go
  ui/pages/accounts/model.go
  ui/pages/accounts/testdata/Test_Snapshot/Visible.golden
  ui/utils/utils.go
  ui/viewport.go
Labels: task
